@0xeed13c1351821b05;
# unique file ID, generated by `capnp id`

struct TangoMapRecord {
  const invalidLSN :UInt32 = 0;
  # 0 represents an invalid LSN (used in a single-sharded scenario)
  logicalSequenceNumber @0 :UInt32 = TangoMapRecord.invalidLSN;
  # LSN should always be > 0 when valid
  payload :union {
    update @1 :Update;
    delete @2 :Delete;
  }
  struct Update {
    key @0 :Text;
    value @1 :Data;
  }
  struct Delete {
    key @0 :Text;
  }
}
